# basic options
title: Waldblog
author: Waldfee
# email: your-email@domain.com
description: News from the forest
# twitter_username: jekyllrb
# github_username:  jekyll

siteurl: /blog

# Build settings
markdown: kramdown
theme: minima
